// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_U52q92nTobldcK_BSx4RypAjbDCwMzI',
    appId: '1:428721630638:web:afbfce0b85e013f254ec3f',
    messagingSenderId: '428721630638',
    projectId: 'music-8fedd',
    authDomain: 'music-8fedd.firebaseapp.com',
    storageBucket: 'music-8fedd.firebasestorage.app',
    measurementId: 'G-6PKJ4F17G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc58_zBKx_3Gw_S3C6ECZNYHRsC6Lxqu4',
    appId: '1:428721630638:android:d1efc8b687d62c5f54ec3f',
    messagingSenderId: '428721630638',
    projectId: 'music-8fedd',
    storageBucket: 'music-8fedd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg-rB-Q8F_ZhjgIi3hB97T-VVn7Lct1DU',
    appId: '1:428721630638:ios:169fe0cf8e07fbc154ec3f',
    messagingSenderId: '428721630638',
    projectId: 'music-8fedd',
    storageBucket: 'music-8fedd.firebasestorage.app',
    iosBundleId: 'com.example.music',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg-rB-Q8F_ZhjgIi3hB97T-VVn7Lct1DU',
    appId: '1:428721630638:ios:169fe0cf8e07fbc154ec3f',
    messagingSenderId: '428721630638',
    projectId: 'music-8fedd',
    storageBucket: 'music-8fedd.firebasestorage.app',
    iosBundleId: 'com.example.music',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_U52q92nTobldcK_BSx4RypAjbDCwMzI',
    appId: '1:428721630638:web:8993a8a6dad838e854ec3f',
    messagingSenderId: '428721630638',
    projectId: 'music-8fedd',
    authDomain: 'music-8fedd.firebaseapp.com',
    storageBucket: 'music-8fedd.firebasestorage.app',
    measurementId: 'G-078ZW7VFG1',
  );

}